name: Upload Solutions

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering from GitHub

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests PyGithub

    - name: Fetch Codeforces Submissions and Upload to GitHub
      run: |
        python update_github.py
      env:
        GITHUB_TOKEN: ${{ secrets.CODEFORCE_TOKEN }}
        CODEFORCES_HANDLE: ${{ secrets.CODEFORCES_HANDLE }}
